### ISSUE TITLE
Whoops, looks like something went wrong.

### ISSUE THREAD

**Issue by tranduchieu** [airmoi/FileMaker#1]
I tested `airmoi/FileMaker` with *Lumen* framework. The result was normal when finding >=1 record(s). But when there were no record found, it had error. Please check it again!

    use airmoi\FileMaker\FileMaker;
    $app->get('/', function() use ($app) {
        // return $app->welcome();
    
        $fm = new FileMaker(db, host, user, password);
        $findCommand = $fm->newFindCommand('Sản phẩm');
        $findCommand->addFindCriterion('Tên', 'váyf');
        $result = $findCommand->execute();
        
        if (FileMaker::isError($result)) {
            echo($result->getMessage());
            return;
        }
        
        $records = $result->getRecords();

        foreach ($records as $record) {
            echo $record->getField('Tên').' '.$record->getField('Giá 1').'<br>';
        }
         
    });

![screenshot 2015-05-14 17 31 51](https://cloud.githubusercontent.com/assets/1744522/7630325/27092196-fa5f-11e4-83c4-89ddaa8a88db.png)

**Comment by airmoi** [comment]
Hi, thanks for testing this library.
The FileMaker::isError function is deprecated (actually I should have removed it from first release) and shouldn't be used with this API as it throws Exceptions instead of returning FileMaker_Error objects as the original API does .

Your code should look like this : 
~~~
[php]
use airmoi\FileMaker\FileMaker;
$app->get('/', function() use ($app) {
    // return $app->welcome();
    try {
        $fm = new FileMaker(db, host, user, password);
        $findCommand = $fm->newFindCommand('Sản phẩm');
        $findCommand->addFindCriterion('Tên', 'váyf');
        $result = $findCommand->execute();
        $records = $result->getRecords();

        foreach ($records as $record) {
            echo $record->getField('Tên').' '.$record->getField('Giá 1').'<br>';
        }
    } catch (FileMakerException $e) {
         echo($e->getMessage());
        return;
    }

});
~~~
