### ISSUE TITLE
Required auto-enter serial fields

### ISSUE THREAD

**Issue by mrchimp** [airmoi/FileMaker#18]
I'm not certain that this is actually an issue, so I would like your opinion.

I have a field which is a `required` `auto-enter serial` field. I am unable to push records to this layout without specifying this field because it is required but I don't want to specify it as it should be auto-generated!

I could remove the "required" validation but that's not quite right either as the field is required to be filled, it just doesn't need to be filled manually.

Should this be something that the library handles?

Is it something the library can handle?

**Comment by airmoi** [comment]
Hi Jake,

As your field is an auto-enter serial, it will be always automatically filled so "required" control is not really necessary here.
Unfortunately, FileMaker's custom web publishing  doesn't provide enough infos to determine wether a required field will be automatically filled if empty so that we may bypass the required rule.

To solve this, you may : 
* Remove the "required" option of your field
* Or remove the field from the layout used to create the record (no validation will be applied on that field then)

**Comment by mrchimp** [comment]
> FileMaker's custom web publishing doesn't provide enough infos 

I thought this might be the case. Thanks for your help.
